# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('center', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ColumnPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('knowledge_graph', models.URLField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 7, 17, 593629))),
                ('progress', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField()),
                ('status', models.CharField(default=b'Not Started', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ModelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_uri', models.URLField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setynuco.MLModel')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 7, 17, 595545))),
                ('finished_on', models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 7, 17, 595574))),
                ('input_file', models.FileField(upload_to=b'')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setynuco.MLModel')),
            ],
        ),
        migrations.AddField(
            model_name='columnprediction',
            name='prediction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setynuco.PredictionRun'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setynuco.MLModel'),
        ),
        migrations.AddField(
            model_name='ccmembership',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setynuco.Cluster'),
        ),
        migrations.AddField(
            model_name='ccmembership',
            name='column_prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setynuco.ColumnPrediction'),
        ),
    ]
