# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setynuco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 52, 35, 183437)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 52, 35, 185341)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='finished_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 52, 35, 185379)),
        ),
    ]
