# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setynuco', '0002_auto_20180531_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 56, 54, 877367)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 56, 54, 879287)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='finished_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 14, 56, 54, 879316)),
        ),
    ]
