# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setynuco', '0003_auto_20180531_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnprediction',
            name='features',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 52, 47, 333719)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 52, 47, 335711)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='finished_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 52, 47, 335740)),
        ),
    ]
