# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setynuco', '0004_auto_20180605_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 18, 25, 34, 676315)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 18, 25, 34, 678373)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='finished_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 18, 25, 34, 678403)),
        ),
    ]
