# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setynuco', '0005_auto_20180608_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrun',
            name='status',
            field=models.CharField(choices=[(b'stopped', b'stopped'), (b'running', b'running'), (b'not started yet', b'not started yet'), (b'finished', b'finished')], default=b'not started yet', max_length=20),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 14, 46, 23, 695536)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 14, 46, 23, 697130)),
        ),
        migrations.AlterField(
            model_name='predictionrun',
            name='finished_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 14, 46, 23, 697157)),
        ),
    ]
